# render.yaml
services:
  - type: web
    name: line-webhook
    env: python
    plan: starter        # ← 有料はこれ 1 個だけ
    startCommand: python webhook_receiver.py
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN   # secrets に登録済みの名前
        sync: false                     # Render のダッシュボード側に入力
      - key: LINE_USER_ID
        sync: false
