# render.yaml
services:
  - type: web                  # Webhook 受信
    name: line-webhook
    env: python
    startCommand: python webhook_receiver.py
    plan: starter
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_USER_ID
        sync: false

  - type: worker               # 1 分ループ
    name: rci-loop
    env: python
    startCommand: python line_rci_alert.py
    plan: starter              # ← 同じ Starter にしておく
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_USER_ID
        sync: false
