name: RCI Alert Bot

on:
  schedule:
    - cron: "*/1 * * * *"  # 毎分実行
  workflow_dispatch:

jobs:
  rci_alert:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 依存ライブラリをインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 通知スクリプトを実行
        env:
          line_channel_access_token: ${{ secrets.line_channel_access_token }}
          line_user_id: ${{ secrets.line_user_id }}
        run: python line_rci_alert.py
