name: Mochipoyo RCI Loop

on:
  schedule:
    - cron:  "*/1 * * * *"      # ← 1 分おき
  workflow_dispatch:            # 手動トリガー

jobs:
  loop:
    runs-on: ubuntu-latest
    # 同時に何本も走ると API 制限に掛かるので 1 本に制限
    concurrency:
      group: rci-loop
      cancel-in-progress: true

    steps:
      # リポジトリ取得
      - uses: actions/checkout@v3

      # Python 3.11 を用意
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 必要パッケージをインストール
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 本体スクリプトを実行
      - name: run line_rci_alert.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID:             ${{ secrets.LINE_USER_ID }}
        run: python line_rci_alert.py
